from __future__ import annotations

from typing import Any, Protocol


class McpBridgeBase(Protocol):
    async def connect(self) -> None: ...

    async def list_tools(self) -> list[dict[str, Any]]: ...

    async def call_tool(self, name: str, arguments: dict[str, Any]) -> str: ...

    async def healthcheck(self) -> bool: ...

    async def close(self) -> None: ...
